package com.kenyarealestate.verification.enums;

public enum OwnershipDocumentCategory {
    TITLE_DEED,
    LAND_SEARCH_CERTIFICATE,
    LAND_RENT_CLEARANCE,
    RATES_CLEARANCE_CERTIFICATE,
    CONSENT_TO_TRANSFER,
    LAND_CONTROL_BOARD_CONSENT,
    TRANSFER_FORM_RL1,
    SURVEY_MAP,
    SPOUSAL_CONSENT,
    MUTATION_FORM,
    LEASE_AGREEMENT,
    LANDLORD_AUTHORIZATION,
    PROBATE_GRANT,
    POWER_OF_ATTORNEY,
    SERVICE_CHARGE_CLEARANCE,
    BUSINESS_PERMIT
}
